services:
  database:
    image: postgres
    restart: always

    env_file:
      - .env.prod
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DB}
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432

  cache:
    image: redis
    restart: always

    ports:
      - 6379

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    ports:
      - 3579:3579
    depends_on:
      - database
      - cache
    networks:
      - default

volumes:
  data:
